# Generated by Django 6.0 on 2025-12-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='patient_docs/'),
        ),
    ]
