# Generated by Django 6.0 on 2025-12-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_patient_registration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='visit',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked / Fee Paid'), ('in_progress', 'Consultation In Progress'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
        migrations.CreateModel(
            name='VisitTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sittings', models.PositiveIntegerField(default=1)),
                ('cost_per_sitting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.treatment')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='emr.visit')),
            ],
        ),
    ]
