# Generated by Django 6.0 on 2025-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_treatment_price_visit_consultation_fee_visit_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='visit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
